name: Release workflow

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'master'
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # 1 - Read version tag from merge-request title
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config user.name "GitHub Actions Bot"
      - run: git config user.email "<>"
      - name: Checkout master
        uses: actions/checkout@master

      # 2 - Read version tag from merge-request title (will be done using regex in next version)
      - name: Log version tag
        run: echo "${{ github.event.pull_request.title }}"

      # 3 - Create tag and release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.pull_request.title }}
          name: Release ${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
